apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app-deployment
  labels:
    app: tomcat-app
spec:
  replicas: 1  # You can increase this number for scaling
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app-container
        image: your-docker-repository/tomcat-app:latest  # Replace with your actual image name
        ports:
        - containerPort: 8000  # Port Tomcat is configured to listen on
        volumeMounts:
        - name: war-file-volume
          mountPath: /usr/local/tomcat/webapps/ROOT.war
      volumes:
        - name: war-file-volume
          emptyDir: {}  # You can replace with a PersistentVolume for permanent storage
