apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-service
spec:
  selector:
    app: tomcat-app
  ports:
    - protocol: TCP
      port: 80   # External port accessible from outside the Kubernetes cluster
      targetPort: 8000  # Port your Tomcat container is listening on
  type: LoadBalancer  # Use LoadBalancer to expose the service externally (or NodePort for specific port mapping)
